/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package mygui;

import java.awt.Image;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;

/**
 *
 * @author Admin
 */
public class WindowButtons extends javax.swing.JPanel {
    
        // Variables declaration - do not modify
    private javax.swing.JButton closeButton;
    private javax.swing.JButton minimizeButton;
    private javax.swing.JButton maximizeButton;
    private ActionListener closeButtonAction;
    private ActionListener minimizeButtonAction;
    private ActionListener maximizeButtonAction;

    /**
     * Creates new form NewJPanel
     */
    public WindowButtons(ActionListener closeButtonActionListener,
            ActionListener minimizeButtonActionListener,
            ActionListener maximizeButtonActionListener) {
        closeButtonAction = closeButtonActionListener;
        minimizeButtonAction = minimizeButtonActionListener;
        maximizeButtonAction = maximizeButtonActionListener;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        closeButton = new javax.swing.JButton();
        minimizeButton = new javax.swing.JButton();
        maximizeButton = new javax.swing.JButton();

        setFocusable(false);
        setOpaque(false);

        closeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mygui/Images/close.png"))); // NOI18N
        closeButton.setBorderPainted(false);
        closeButton.setContentAreaFilled(false);
        closeButton.setFocusable(false);
        closeButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/mygui/Images/close_pressed.png"))); // NOI18N
        closeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/mygui/Images/close_hover.png"))); // NOI18N
        closeButton.addActionListener(closeButtonAction);
        
        maximizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mygui/Images/maximize.png"))); // NOI18N
        maximizeButton.setBorderPainted(false);
        maximizeButton.setContentAreaFilled(false);
        maximizeButton.setFocusable(false);
        maximizeButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/mygui/Images/maximize_pressed.png"))); // NOI18N
        maximizeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/mygui/Images/maximize_hover.png"))); // NOI18N
        maximizeButton.addActionListener(maximizeButtonAction);

        minimizeButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/mygui/Images/minimize.png"))); // NOI18N
        minimizeButton.setBorderPainted(false);
        minimizeButton.setContentAreaFilled(false);
        minimizeButton.setFocusable(false);
        minimizeButton.setPressedIcon(new javax.swing.ImageIcon(getClass().getResource("/mygui/Images/minimize_pressed.png"))); // NOI18N
        minimizeButton.setRolloverIcon(new javax.swing.ImageIcon(getClass().getResource("/mygui/Images/minimize_hover.png"))); // NOI18N
        minimizeButton.addActionListener(minimizeButtonAction);



        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addGroup(layout.createSequentialGroup().addGap(6, 6, 6).addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 9, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(minimizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 13, javax.swing.GroupLayout.PREFERRED_SIZE).addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED).addComponent(maximizeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE).addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING).addComponent(maximizeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 12, Short.MAX_VALUE).addComponent(minimizeButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE).addComponent(closeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE));
    }
}
